CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title             VARCHAR(255)                            NOT NULL,
    annotation        VARCHAR                                 NOT NULL,
    created           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    paid              BOOLEAN                                 NOT NULL,
    initiator         BIGINT                                  NOT NULL,
    category          BIGINT                                  NOT NULL,
    participantLimit  BIGINT,
    requestModeration BOOLEAN                                 NOT NULL,
    publishedOn       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    state             VARCHAR,
    confirmedRequests INTEGER,

    CONSTRAINT pk_item PRIMARY KEY (id),
    FOREIGN KEY (initiator) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (initiator) REFERENCES categories (id) ON DELETE CASCADE,
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status       VARCHAR,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned     BOOLEAN                                 NOT NULL,
    title     VARCHAR,
    CONSTRAINT pk_bookings PRIMARY KEY (id),
);