CREATE TABLE IF NOT EXISTS hits
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app         VARCHAR(255)                            NOT NULL,
    uri         VARCHAR(255)                            NOT NULL,
    ip          VARCHAR(16)                             NOT NULL,
    views_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
);